import type { SpellingBank } from "./types";

export const PACK_5: SpellingBank = {
  id: "pack-5",
  label: "Pack 5",
  words: [
    { word: "left", sentence: "I left my hat on the school bus this morning." },
    { word: "ship", sentence: "A big ship sailed slowly across the harbor." },
    { word: "train", sentence: "We rode the train all the way to grandma's house." },
    { word: "saw", sentence: "I saw a tiny ladybug crawl across the window." },
    { word: "pay", sentence: "I will pay for the gum with my own coins." },
    { word: "large", sentence: "A large pumpkin grew in our garden this fall." },
    { word: "near", sentence: "The bus stop is near our front gate." },
    { word: "down", sentence: "Please sit down on the rug for story time." },
    { word: "dawn", sentence: "The birds sang loudly at dawn this morning." },
    { word: "bill", sentence: "Dad opened the water bill at the kitchen table." },
    { word: "want", sentence: "I want a warm bowl of soup for lunch." },
    { word: "girls", sentence: "All the girls in my class wore party hats." },
    { word: "part", sentence: "The hardest part of the puzzle was the blue sky." },
    { word: "still", sentence: "Please sit still while I brush your hair." },
    { word: "place", sentence: "This is a quiet place to read my book." },
    { word: "report", sentence: "She wrote a short report about her pet rabbit." },
    { word: "never", sentence: "I have never tasted such sweet honey before." },
    { word: "found", sentence: "I found a shiny rock by the little creek." },
    { word: "why", sentence: "Tell me why the sky looks pink at sunset." },
    { word: "seesaw", sentence: "We took turns on the seesaw at recess." },
    { word: "bedtime", sentence: "It is bedtime, so brush your teeth and pick a book." },
    { word: "sunset", sentence: "The sunset turned the clouds bright orange and pink." },
    { word: "bathtub", sentence: "My little brother loves splashing in the bathtub." },
    { word: "flagpole", sentence: "A red flag waved from the tall flagpole at school." },
    { word: "backpack", sentence: "I packed my lunchbox inside my green backpack." },
    { word: "sailboat", sentence: "A white sailboat drifted past us on the calm lake." },
    { word: "raincoat", sentence: "Wear your yellow raincoat outside, it is pouring." },
    { word: "inside", sentence: "Bring the wet umbrella inside and shake it off." },
    { word: "himself", sentence: "My brother tied his shoes all by himself today." },
  ],
};
