import type { SpellingBank } from "./types";

export const PACK_1: SpellingBank = {
  id: "pack-1",
  label: "Pack 1",
  words: [
    { word: "season", sentence: "Fall is my favorite season because of the colorful leaves." },
    { word: "sign", sentence: "We saw a sign that said the park was open." },
    { word: "space", sentence: "There is plenty of space on the rug to play." },
    { word: "wagon", sentence: "I pulled my little brother in the red wagon." },
    { word: "wheat", sentence: "The farmer grew wheat in the big field." },
    { word: "window", sentence: "Birds sang outside my bedroom window this morning." },
    { word: "black", sentence: "She wore black boots in the rain." },
    { word: "catch", sentence: "Try to catch the ball with both hands." },
    { word: "catcher", sentence: "The catcher in baseball wears a special mask." },
    { word: "kitchen", sentence: "We baked cookies in the kitchen after lunch." },
    { word: "butcher", sentence: "The butcher wrapped our meat in white paper." },
    { word: "warm", sentence: "My hot cocoa kept my hands warm at the bus stop." },
    { word: "unless", sentence: "We cannot leave unless we put on our coats." },
    { word: "able", sentence: "Are you able to tie your own shoes yet?" },
    { word: "clothing", sentence: "She picked out warm clothing for the snow day." },
    { word: "clothes", sentence: "I folded my clean clothes and put them away." },
    { word: "clothe", sentence: "Mom helps clothe my baby brother every morning." },
    { word: "began", sentence: "Class began with a song about the days of the week." },
    { word: "begin", sentence: "We begin every morning with a quiet reading time." },
    { word: "beginning", sentence: "At the beginning of the book, the dog gets lost." },
    { word: "soon", sentence: "We will eat dinner soon, so wash your hands." },
    { word: "noon", sentence: "We have lunch at noon every school day." },
    { word: "new", sentence: "She got a new pencil case for her birthday." },
    { word: "zoo", sentence: "We saw a giant elephant at the zoo." },
    { word: "boot", sentence: "I lost one rubber boot in the deep mud." },
    { word: "too", sentence: "I want to come too, please wait for me." },
    { word: "moon", sentence: "The full moon was bright in the sky last night." },
    { word: "blew", sentence: "The strong wind blew my hat off my head." },
    { word: "soup", sentence: "Hot tomato soup is my favorite lunch on cold days." },
    { word: "you", sentence: "Can you reach the top of the bookshelf?" },
  ],
};
