import type { SpellingBank } from "./types";

export const PACK_4: SpellingBank = {
  id: "pack-4",
  label: "Pack 4",
  words: [
    { word: "boat", sentence: "We rowed a small boat across the calm lake." },
    { word: "son", sentence: "Her son brought home a painting from school." },
    { word: "hard", sentence: "The cookie was too hard to bite at first." },
    { word: "fire", sentence: "We sat by the warm fire and roasted marshmallows." },
    { word: "age", sentence: "What is your age on your next birthday?" },
    { word: "fine", sentence: "I feel fine after a good night of sleep." },
    { word: "cannot", sentence: "I cannot find my other rubber boot anywhere." },
    { word: "rest", sentence: "Take a short rest before we walk back home." },
    { word: "sun", sentence: "The bright sun warmed the picnic blanket all afternoon." },
    { word: "race", sentence: "I won the race at our school field day." },
    { word: "wire", sentence: "Be careful of the loose wire near the fence." },
    { word: "gold", sentence: "She found a tiny gold ring in the sand." },
    { word: "red", sentence: "My favorite crayon is bright cherry red." },
    { word: "line", sentence: "Please get in line behind your friend." },
    { word: "east", sentence: "The sun rises in the east every morning." },
    { word: "help", sentence: "Can you help me carry this heavy bag?" },
    { word: "cover", sentence: "Please cover the leftover food before bedtime." },
    { word: "tire", sentence: "Dad fixed the flat tire on my bike." },
    { word: "read", sentence: "I love to read picture books at bedtime." },
    { word: "read", sentence: "I read that whole story last night." },
    { word: "how", sentence: "How did you fix the broken toy?" },
    { word: "now", sentence: "Please put on your coat now, the bus is coming." },
    { word: "cow", sentence: "The cow stood in the field eating grass." },
    { word: "owl", sentence: "An owl hooted from the tall oak tree." },
    { word: "ouch", sentence: "Ouch, that splinter hurt my finger!" },
    { word: "house", sentence: "Our house has a bright red front door." },
    { word: "found", sentence: "I found my missing sock under the bed." },
    { word: "out", sentence: "Please put the empty box out by the curb." },
    { word: "gown", sentence: "She wore a long gown to the school play." },
    { word: "town", sentence: "Our small town has only one bookstore." },
  ],
};
