import type { SpellingBank } from "./types";

export const PACK_3: SpellingBank = {
  id: "pack-3",
  label: "Pack 3",
  words: [
    { word: "price", sentence: "The price of the toy is on the little tag." },
    { word: "become", sentence: "Caterpillars become beautiful butterflies after a while." },
    { word: "class", sentence: "Our class went to the library this morning." },
    { word: "horse", sentence: "The brown horse galloped across the grassy field." },
    { word: "care", sentence: "Take good care of your library books." },
    { word: "try", sentence: "Try one bite of the new vegetable, please." },
    { word: "move", sentence: "Please move your chair closer to the table." },
    { word: "delay", sentence: "Heavy snow caused a long delay on the bus route." },
    { word: "pound", sentence: "I weighed a pound of fresh apples at the store." },
    { word: "behind", sentence: "Hide behind the big tree during the game." },
    { word: "around", sentence: "We walked around the lake on a sunny day." },
    { word: "burn", sentence: "Be careful not to burn yourself on the hot pan." },
    { word: "camp", sentence: "We will camp in a tent by the lake this summer." },
    { word: "clear", sentence: "The lake water was so clear we could see fish." },
    { word: "bear", sentence: "A friendly bear waved at us from the picture book." },
    { word: "bare", sentence: "I felt the cold floor with my bare feet." },
    { word: "clean", sentence: "I helped clean my room before bedtime." },
    { word: "spell", sentence: "Can you spell your last name out loud?" },
    { word: "poor", sentence: "The poor little kitten was hungry and lost." },
    { word: "finish", sentence: "Please finish your homework before you watch TV." },
    { word: "thing", sentence: "What is that funny thing on the kitchen table?" },
    { word: "think", sentence: "I think tomorrow will be a great day." },
    { word: "long", sentence: "The line to the slide was very long today." },
    { word: "thank", sentence: "I want to thank you for the kind gift." },
    { word: "pitch", sentence: "Watch the player pitch the ball over home plate." },
    { word: "pitches", sentence: "The coach pitches the ball gently for new players." },
    { word: "cent", sentence: "I have one shiny cent in my pocket." },
    { word: "cents", sentence: "The gum costs only twenty-five cents." },
    { word: "catch", sentence: "I will catch the bus right after school." },
    { word: "catches", sentence: "She always catches the ball with one hand." },
  ],
};
